# Generated by Django 4.2.2 on 2024-04-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=70, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Categoria')),
                ('nombreProducto', models.CharField(max_length=70, verbose_name='Nombre del Producto')),
                ('valorProducto', models.IntegerField(verbose_name='Valor del Producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
